[package]
name = "crud-tutorial"
version = "0.1.0"
edition = "2021"

[lib]
name = "crud"
crate-type = ["cdylib", "lib"]

[dependencies]
# borsh = "1.3.1"
borsh = { version = "1.3.1", features = ["derive"] }
solana-program = "1.17.17"
thiserror = "1.0.56"
